version: "3.7"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - .:/urs/src/app
      - /usr/src/app/node_modules
    ports:
      - 4000:4000
